Logic for checking out and syncing from the mainline project repo
civiform/civiform-deploy pull request #1
Opened 2022-02-02 04:57 UTC by bion

2022-02-03 01:59 UTC, goldblatt requested changes

2022-02-03 01:59 UTC, goldblatt commented on bin/lib/checkout.sh
> +  echo '/cloud' >> .git/info/sparse-checkout
nit: does this need single quotes or can we use double

2022-02-03 01:59 UTC, goldblatt commented on bin/deploy
> +# DOC: Deploy an image to an environment. Usage: deploy [--tag=imageTag] [env]; env defaults to "staging", tag defaults to "latest".
i feel like the naming here is a lil confusing to me as it's not deploying anything is it?

2022-02-03 02:05 UTC, bion commented on bin/lib/checkout.sh
> +  echo '/cloud' >> .git/info/sparse-checkout
done

2022-02-03 02:06 UTC, bion commented on bin/deploy
> +# DOC: Deploy an image to an environment. Usage: deploy [--tag=imageTag] [env]; env defaults to "staging", tag defaults to "latest".
Yep, this script isn't fully implemented yet. The checkout system is meant to be transparent to the user so I just chose one of the commands we plan to implement to serve as a stub to get this first piece of functionality in.

2022-02-03 02:08 UTC, goldblatt commented on bin/deploy
> +# DOC: Deploy an image to an environment. Usage: deploy [--tag=imageTag] [env]; env defaults to "staging", tag defaults to "latest".
right right it does say that in the pr

2022-02-03 02:11 UTC, goldblatt commented on bin/lib/snapshots.sh
> +  [[ "${full_tag}" =~ ^SNAPSHOT\-[a-zA-Z0-9]+\-[0-9]+$ ]]
nit: i think you can make this a variable

2022-02-03 02:14 UTC, goldblatt commented on bin/deploy
> +if snapshots::tag_is_snapshot "${image_tag}"; then
would say lil confused by the terminology here like tag, snapshot and sha all seem like the are kind of similar. image_tag also seems lil confusing to me. struggling to get my git terminology. would maybe just add some comments here?

2022-02-03 02:15 UTC, bion commented on bin/lib/snapshots.sh
> +  [[ "${full_tag}" =~ ^SNAPSHOT\-[a-zA-Z0-9]+\-[0-9]+$ ]]
the regex?

2022-02-03 02:15 UTC, goldblatt commented on bin/lib/snapshots.sh
> +  [[ "${full_tag}" =~ ^SNAPSHOT\-[a-zA-Z0-9]+\-[0-9]+$ ]]
yeah

2022-02-03 02:16 UTC, goldblatt reviewed
approve with kind of caveat that i think some of the terminology could use a comment or two

2022-02-03 02:17 UTC, goldblatt approved these changes

2022-02-03 02:41 UTC, bion commented on bin/lib/snapshots.sh
> +  [[ "${full_tag}" =~ ^SNAPSHOT\-[a-zA-Z0-9]+\-[0-9]+$ ]]
done

2022-02-03 02:59 UTC, bion commented on bin/deploy
> +if snapshots::tag_is_snapshot "${image_tag}"; then
Added some comments and factored out another (hopefully well-named) function. PTAL

2022-02-03 17:08 UTC, goldblatt commented on bin/lib/checkout.sh
> +function checkout::sync() {
would maybe call this at_main() instead of sync?

2022-02-03 17:08 UTC, goldblatt commented on bin/lib/snapshots.sh
> +# A snapshot tag is a docker image tag assigned to CiviForm images when they are
this was super super helpful thanks for adding this in

2022-02-03 17:09 UTC, goldblatt commented on bin/deploy
> +if snapshots::tag_is_snapshot "${image_tag}"; then
A++++ super helpful

2022-02-03 22:47 UTC, bion commented on bin/lib/checkout.sh
> +function checkout::sync() {
done

2022-02-03 23:52 UTC, zaralouis-sf approved these changes
Everything looks good to me!

2022-02-08 02:06 UTC, shanemc-goog commented on bin/lib/snapshots.sh
> +readonly CIVIFORM_SNAPSHOT_TAG_REGEX="^SNAPSHOT\-([a-zA-Z0-9]+)\-[0-9]+$"
[0-9] -> \d

2022-02-08 02:49 UTC, bion commented on bin/deploy
> +#! /usr/bin/env bash
executables should have no extension, library code should have .sh: https://google.github.io/styleguide/shellguide.html#s2.1-file-extensions

2022-02-08 02:49 UTC, bion commented on bin/lib/snapshots.sh
> +readonly CIVIFORM_SNAPSHOT_TAG_REGEX="^SNAPSHOT\-([a-zA-Z0-9]+)\-[0-9]+$"
i could not get that to work, i do not know why

2022-02-08 03:00 UTC, shanemc-goog commented on bin/lib/snapshots.sh
> +readonly CIVIFORM_SNAPSHOT_TAG_REGEX="^SNAPSHOT\-([a-zA-Z0-9]+)\-[0-9]+$"
\\d maybe? but no worries

2022-02-08 03:00 UTC, shanemc-goog approved these changes

2022-02-08 03:03 UTC, bion commented on bin/lib/snapshots.sh
> +readonly CIVIFORM_SNAPSHOT_TAG_REGEX="^SNAPSHOT\-([a-zA-Z0-9]+)\-[0-9]+$"
> The irony that I had to write that with 4 \ s :D
😆 

I tried it with a variety of different numbers of backslashes to no avail 🤷🏻

2022-02-08 18:10 UTC, shubha-rajan approved these changes

2022-02-08 19:13 UTC, merged